[project]
name = "fairness-rectification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deeplake>=4.1.11",
    "pydrive2>=1.21.3",
]
